name: Android NuGet Generation
permissions:
  contents: write
  pull-requests: write 
  packages: write
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{github.token}}        

      - name: Build solution and generate NuGet package
        run: |  
          cd Facebook.Android/source/facebook-core/
          sudo dotnet workload install maui maui-android android
          dotnet pack -c Release -o out

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./Facebook.Android/source/facebook-core/out/*.nupkg --skip-duplicate --no-symbols true
